name: Publish

on:
  release:
    types: [created]

jobs:
  #
  # npm job
  #
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          always-auth: true
          registry-url: https://registry.npmjs.org
      # Dependencies
      - id: cache_npm
        name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules.tar.zstd
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-
      - name: Install dependencies with NPM
        if: steps.cache_npm.outputs.cache-hit != 'true'
        run: npm ci
      - name: Unarchive node_modules
        if: steps.cache_npm.outputs.cache-hit == 'true'
        run: tar --use-compress-program "zstd -d --long=31" -xf node_modules.tar.zstd
      # Build
      - name: Build application
        run: yarn build
        env:
          CI: true
      - name: Check build worked correctly
        run: |
          if [ ! -f ./packages/core/lib/index.js ]; then
            echo "Something went wrong: no ./packages/core/lib/index.js file was built!"
            exit 1
          else
            echo "Build appears to be successful: ./packages/core/lib/index.js was created"
          fi
      # Publish
      - name: Publish release to NPM registry
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISHING }}
